# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'MasjidTimeTable' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Codeable Practice

  pod 'Alamofire'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'IQKeyboardManager'
  pod 'AEXML'
  pod 'lame'
  pod 'ImageViewer'
  #pod 'CropPickerController'
  pod 'CropPickerView'
end
